FROM node:18.17.0-alpine

COPY ./src /home/app/src
COPY ./jest.config.js /home/app/
COPY ./launch.json /home/app/
COPY ./package.json /home/app/
COPY ./swagger.json /home/app/
COPY ./tsconfig.json /home/app/

ENV HOME=/home/app
WORKDIR $HOME

RUN npm install

EXPOSE 5000

CMD ["npm", "start"]